In [1]:
import requests
import pandas as pd
import json
import sys
sys.path.append('../')
from dateutil import parser
from infrastructure.instrument_collection import instrumentCollection
# from datetime import datetime as datetime
from datetime import timedelta, datetime

In [2]:
API_KEY = "69f109a1f4f5cc5df743768870afa57d-7eeba7f9b30b063c75a4c3e6fceeb083"
ACCOUNT_ID = "101-004-29766214-001"
OANDA_URL = "https://api-fxpractice.oanda.com/v3" #"https://api-fxpractice.oanda.com"

In [3]:
session = requests.Session()

In [4]:
session.headers.update({"Authorization": f"Bearer {API_KEY}", "Content-Type":"application/json"})

In [5]:
params = dict(count=10, price="MBA",granularity="H1" )

In [6]:
#url = f"{OANDA_URL}/accounts/{ACCOUNT_ID}/instruments"

In [7]:
#response = session.get(url,params=None, data=None, headers=None)

In [8]:
#session.headers

In [9]:
#response.status_code

In [10]:
#data = response.json()

In [11]:
#data_instruments = data['instruments']

In [12]:
#data['instruments'][0].keys()

In [13]:
#key_i = ['name', 'type', 'displayName', 'pipLocation', 'displayPrecision','tradeUnitsPrecision','marginRate']

In [14]:
#instruments = {}
#for i in data_instruments:
#    key = i['name']
#    instruments[key] = { j:i[j] for j in key_i }
# instruments

In [15]:
#with open("../data/instruments.json","w") as f:
#    f.write(json.dumps(instruments,indent=2))

In [16]:
instruments_list = ["EUR", "USD", "JPY", "CAD"]
inst_names_list = []
for i in instruments_list:
    for j in instruments_list:
        instrument_name = f"{i}_{j}"
        inst_names_list.append(instrument_name)
inst_names_list

['EUR_EUR',
 'EUR_USD',
 'EUR_JPY',
 'EUR_CAD',
 'USD_EUR',
 'USD_USD',
 'USD_JPY',
 'USD_CAD',
 'JPY_EUR',
 'JPY_USD',
 'JPY_JPY',
 'JPY_CAD',
 'CAD_EUR',
 'CAD_USD',
 'CAD_JPY',
 'CAD_CAD']

In [17]:
# instrumentCollection=InstrumentCollection()
instrumentCollection.LoadInstruments("../data")
# instrumentCollection.instruments_dict
myinstrument =  instrumentCollection.instruments_dict
for instrument in inst_names_list:
    if instrument in myinstrument.keys():
        print(instrument)

EUR_USD
EUR_JPY
EUR_CAD
USD_JPY
USD_CAD
CAD_JPY

In [18]:
duration={"S5": 5,
"S10": 10, 
"S15": 15,
"S30": 30,
"M1":60,
"M2": 120,
"M4" :4*60, 
"M5": 5*60 ,
"M10" :10*60 ,
"M15": 15*60 ,
"M30" :30*60 ,
"H1" :1*60*60,
"H2": 2*60*60,
"H3" :3*60*60,
"H4" :4*60*60,
"H6" :6*60*60, 
"H8": 8*60*60,
"H12":12*60*60,
"D":24*60*60,
"W" :7*24*60*60*60, 
"M":31*24*60*60*60}

In [19]:

def getCandlesData(pair,price="MAB",granularity="M1",fromdate=datetime(2020, 5, 17),enddate= datetime(2020, 8, 17)):
    candles_url = f"{OANDA_URL}/instruments/{pair}/candles"
    params = dict(price =price, granularity=granularity)
    params['from']=fromdate.strftime("%Y-%m-%dT%H:%M:%SZ")
    params['to']=enddate.strftime("%Y-%m-%dT%H:%M:%SZ")
    print(params['from'],params['to'])
    response  = session.get(candles_url, params=params, data= None)
    if(response.status_code ==200):
        data = response.json()
        candles = data['candles']
        return candles
    else :
        print (f"Error {response.json()}")
        return false

In [48]:
count= 5000
pair = "EUR_JPY"
granularity="M1"
start_date = datetime(2024, 1, 1)
# gmt palava
to_date = datetime.now() - timedelta(hours=2) 
print("na date be this",to_date)
# end_date = end.strftime("%Y-%m-%dT%H:%M:%SZ")
# start_date = start_date.strftime("%Y-%m-%dT%H:%M:%SZ")
# midbreak = midbreak.strftime("%Y-%m-%dT%H:%M:%SZ")
full_data =[]
data_len = 0
while start_date < to_date:
    end_date = start_date + timedelta(seconds= (count*duration[granularity]))
    print("na end date be this",end_date)
    if end_date > to_date:
        print("longer")
        end_date = to_date
        print(end_date)
    candles = getCandlesData(pair,price="MAB",granularity=granularity,fromdate = start_date,enddate=end_date)
    full_data+=(candles)
    print(f'got {len(candles)} data')
    start_date = end_date
print("done ..........")
# final_df = pd.concat(dfs)

na date be this 2024-09-08 17:13:13.127285
na end date be this 2024-01-04 11:20:00
2024-01-01T00:00:00Z 2024-01-04T11:20:00Z
got 3661 data
na end date be this 2024-01-07 22:40:00
2024-01-04T11:20:00Z 2024-01-07T22:40:00Z
got 2104 data
na end date be this 2024-01-11 10:00:00
2024-01-07T22:40:00Z 2024-01-11T10:00:00Z
got 4984 data
na end date be this 2024-01-14 21:20:00
2024-01-11T10:00:00Z 2024-01-14T21:20:00Z
got 2153 data
na end date be this 2024-01-18 08:40:00
2024-01-14T21:20:00Z 2024-01-18T08:40:00Z
got 4930 data
na end date be this 2024-01-21 20:00:00
2024-01-18T08:40:00Z 2024-01-21T20:00:00Z
got 2231 data
na end date be this 2024-01-25 07:20:00
2024-01-21T20:00:00Z 2024-01-25T07:20:00Z
got 4854 data
na end date be this 2024-01-28 18:40:00
2024-01-25T07:20:00Z 2024-01-28T18:40:00Z
got 2310 data
na end date be this 2024-02-01 06:00:00
2024-01-28T18:40:00Z 2024-02-01T06:00:00Z
got 4766 data
na end date be this 2024-02-04 17:20:00
2024-02-01T06:00:00Z 2024-02-04T17:20:00Z
got 2393 data
na end date be this 2024-02-08 04:40:00
2024-02-04T17:20:00Z 2024-02-08T04:40:00Z
got 4689 data
na end date be this 2024-02-11 16:00:00
2024-02-08T04:40:00Z 2024-02-11T16:00:00Z
got 2462 data
na end date be this 2024-02-15 03:20:00
2024-02-11T16:00:00Z 2024-02-15T03:20:00Z
got 4602 data
na end date be this 2024-02-18 14:40:00
2024-02-15T03:20:00Z 2024-02-18T14:40:00Z
got 2551 data
na end date be this 2024-02-22 02:00:00
2024-02-18T14:40:00Z 2024-02-22T02:00:00Z
got 4537 data
na end date be this 2024-02-25 13:20:00
2024-02-22T02:00:00Z 2024-02-25T13:20:00Z
got 2635 data
na end date be this 2024-02-29 00:40:00
2024-02-25T13:20:00Z 2024-02-29T00:40:00Z
got 4454 data
na end date be this 2024-03-03 12:00:00
2024-02-29T00:40:00Z 2024-03-03T12:00:00Z
got 2716 data
na end date be this 2024-03-06 23:20:00
2024-03-03T12:00:00Z 2024-03-06T23:20:00Z
got 4381 data
na end date be this 2024-03-10 10:40:00
2024-03-06T23:20:00Z 2024-03-10T10:40:00Z
got 2795 data
na end date be this 2024-03-13 22:00:00
2024-03-10T10:40:00Z 2024-03-13T22:00:00Z
got 4361 data
na end date be this 2024-03-17 09:20:00
2024-03-13T22:00:00Z 2024-03-17T09:20:00Z
got 2815 data
na end date be this 2024-03-20 20:40:00
2024-03-17T09:20:00Z 2024-03-20T20:40:00Z
got 4264 data
na end date be this 2024-03-24 08:00:00
2024-03-20T20:40:00Z 2024-03-24T08:00:00Z
got 2889 data
na end date be this 2024-03-27 19:20:00
2024-03-24T08:00:00Z 2024-03-27T19:20:00Z
got 4199 data
na end date be this 2024-03-31 06:40:00
2024-03-27T19:20:00Z 2024-03-31T06:40:00Z
got 2964 data
na end date be this 2024-04-03 18:00:00
2024-03-31T06:40:00Z 2024-04-03T18:00:00Z
got 4105 data
na end date be this 2024-04-07 05:20:00
2024-04-03T18:00:00Z 2024-04-07T05:20:00Z
got 3049 data
na end date be this 2024-04-10 16:40:00
2024-04-07T05:20:00Z 2024-04-10T16:40:00Z
got 4048 data
na end date be this 2024-04-14 04:00:00
2024-04-10T16:40:00Z 2024-04-14T04:00:00Z
got 3132 data
na end date be this 2024-04-17 15:20:00
2024-04-14T04:00:00Z 2024-04-17T15:20:00Z
got 3957 data
na end date be this 2024-04-21 02:40:00
2024-04-17T15:20:00Z 2024-04-21T02:40:00Z
got 3210 data
na end date be this 2024-04-24 14:00:00
2024-04-21T02:40:00Z 2024-04-24T14:00:00Z
got 3880 data
na end date be this 2024-04-28 01:20:00
2024-04-24T14:00:00Z 2024-04-28T01:20:00Z
got 3288 data
na end date be this 2024-05-01 12:40:00
2024-04-28T01:20:00Z 2024-05-01T12:40:00Z
got 3790 data
na end date be this 2024-05-05 00:00:00
2024-05-01T12:40:00Z 2024-05-05T00:00:00Z
got 3356 data
na end date be this 2024-05-08 11:20:00
2024-05-05T00:00:00Z 2024-05-08T11:20:00Z
got 3722 data
na end date be this 2024-05-11 22:40:00
2024-05-08T11:20:00Z 2024-05-11T22:40:00Z
got 3450 data
na end date be this 2024-05-15 10:00:00
2024-05-11T22:40:00Z 2024-05-15T10:00:00Z
got 3637 data
na end date be this 2024-05-18 21:20:00
2024-05-15T10:00:00Z 2024-05-18T21:20:00Z
got 3529 data
na end date be this 2024-05-22 08:40:00
2024-05-18T21:20:00Z 2024-05-22T08:40:00Z
got 3382 data
na end date be this 2024-05-25 20:00:00
2024-05-22T08:40:00Z 2024-05-25T20:00:00Z
got 3612 data
na end date be this 2024-05-29 07:20:00
2024-05-25T20:00:00Z 2024-05-29T07:20:00Z
got 3472 data
na end date be this 2024-06-01 18:40:00
2024-05-29T07:20:00Z 2024-06-01T18:40:00Z
got 3690 data
na end date be this 2024-06-05 06:00:00
2024-06-01T18:40:00Z 2024-06-05T06:00:00Z
got 3407 data
na end date be this 2024-06-08 17:20:00
2024-06-05T06:00:00Z 2024-06-08T17:20:00Z
got 3772 data
na end date be this 2024-06-12 04:40:00
2024-06-08T17:20:00Z 2024-06-12T04:40:00Z
got 3319 data
na end date be this 2024-06-15 16:00:00
2024-06-12T04:40:00Z 2024-06-15T16:00:00Z
got 3841 data
na end date be this 2024-06-19 03:20:00
2024-06-15T16:00:00Z 2024-06-19T03:20:00Z
got 3244 data
na end date be this 2024-06-22 14:40:00
2024-06-19T03:20:00Z 2024-06-22T14:40:00Z
got 3922 data
na end date be this 2024-06-26 02:00:00
2024-06-22T14:40:00Z 2024-06-26T02:00:00Z
got 3165 data
na end date be this 2024-06-29 13:20:00
2024-06-26T02:00:00Z 2024-06-29T13:20:00Z
got 4012 data
na end date be this 2024-07-03 00:40:00
2024-06-29T13:20:00Z 2024-07-03T00:40:00Z
got 3084 data
na end date be this 2024-07-06 12:00:00
2024-07-03T00:40:00Z 2024-07-06T12:00:00Z
got 4088 data
na end date be this 2024-07-09 23:20:00
2024-07-06T12:00:00Z 2024-07-09T23:20:00Z
got 2991 data
na end date be this 2024-07-13 10:40:00
2024-07-09T23:20:00Z 2024-07-13T10:40:00Z
got 4157 data
na end date be this 2024-07-16 22:00:00
2024-07-13T10:40:00Z 2024-07-16T22:00:00Z
got 2914 data
na end date be this 2024-07-20 09:20:00
2024-07-16T22:00:00Z 2024-07-20T09:20:00Z
got 4251 data
na end date be this 2024-07-23 20:40:00
2024-07-20T09:20:00Z 2024-07-23T20:40:00Z
got 2835 data
na end date be this 2024-07-27 08:00:00
2024-07-23T20:40:00Z 2024-07-27T08:00:00Z
got 4322 data
na end date be this 2024-07-30 19:20:00
2024-07-27T08:00:00Z 2024-07-30T19:20:00Z
got 2746 data
na end date be this 2024-08-03 06:40:00
2024-07-30T19:20:00Z 2024-08-03T06:40:00Z
got 4400 data
na end date be this 2024-08-06 18:00:00
2024-08-03T06:40:00Z 2024-08-06T18:00:00Z
got 2682 data
na end date be this 2024-08-10 05:20:00
2024-08-06T18:00:00Z 2024-08-10T05:20:00Z
got 4470 data
na end date be this 2024-08-13 16:40:00
2024-08-10T05:20:00Z 2024-08-13T16:40:00Z
got 2588 data
na end date be this 2024-08-17 04:00:00
2024-08-13T16:40:00Z 2024-08-17T04:00:00Z
got 4557 data
na end date be this 2024-08-20 15:20:00
2024-08-17T04:00:00Z 2024-08-20T15:20:00Z
got 2514 data
na end date be this 2024-08-24 02:40:00
2024-08-20T15:20:00Z 2024-08-24T02:40:00Z
got 4645 data
na end date be this 2024-08-27 14:00:00
2024-08-24T02:40:00Z 2024-08-27T14:00:00Z
got 2446 data
na end date be this 2024-08-31 01:20:00
2024-08-27T14:00:00Z 2024-08-31T01:20:00Z
got 4722 data
na end date be this 2024-09-03 12:40:00
2024-08-31T01:20:00Z 2024-09-03T12:40:00Z
got 2349 data
na end date be this 2024-09-07 00:00:00
2024-09-03T12:40:00Z 2024-09-07T00:00:00Z
got 4801 data
na end date be this 2024-09-10 11:20:00
longer
2024-09-08 17:13:13.127285
2024-09-07T00:00:00Z 2024-09-08T17:13:13Z
got 0 data
done ..........

In [49]:
# S5	5 second candlesticks, minute alignment
# S10	10 second candlesticks, minute alignment
# S15	15 second candlesticks, minute alignment
# S30	30 second candlesticks, minute alignment
# M1	1 minute candlesticks, minute alignment
# M2	2 minute candlesticks, hour alignment
# M4	4 minute candlesticks, hour alignment
# M5	5 minute candlesticks, hour alignment
# M10	10 minute candlesticks, hour alignment
# M15	15 minute candlesticks, hour alignment
# M30	30 minute candlesticks, hour alignment
# H1	1 hour candlesticks, hour alignment
# H2	2 hour candlesticks, day alignment
# H3	3 hour candlesticks, day alignment
# H4	4 hour candlesticks, day alignment
# H6	6 hour candlesticks, day alignment
# H8	8 hour candlesticks, day alignment
# H12	12 hour candlesticks, day alignment
# D	1 day candlesticks, day alignment
# W	1 week candlesticks, aligned to start of week
# M	1 month candlesticks, aligned to first day of the month

In [50]:
len(full_data)

256253

In [51]:
candles_list  = []
for acandle in full_data:
    new_dict = {}
    new_dict['time'] = acandle['time']
    new_dict['mid_o'] = float(acandle['mid']['o'])
    new_dict['mid_h'] = float(acandle['mid']['h'])
    new_dict['mid_l'] = float(acandle['mid']['l'])
    new_dict['mid_c'] = float(acandle['mid']['c'])
    new_dict['ask_o'] = float(acandle['ask']['o'])
    new_dict['ask_h'] = float(acandle['ask']['h'])
    new_dict['ask_l'] = float(acandle['ask']['l'])
    new_dict['ask_c'] = float(acandle['ask']['c'])
    new_dict['bid_o'] = float(acandle['bid']['o'])
    new_dict['bid_h'] = float(acandle['bid']['h'])
    new_dict['bid_l'] = float(acandle['bid']['l'])
    new_dict['bid_c'] = float(acandle['bid']['c'])
    
    candles_list.append(new_dict)
# candles_list

In [52]:
filename=f"../data/my_candles{pair}_{granularity}.json"
with open(filename,'w') as f:
    f.write(json.dumps(candles_list, indent=4))

In [53]:
df = pd.read_json(filename)
df
# candles = getCandlesData("EUR_CAD",granularity="M1")

,time,mid_o,mid_h,mid_l,mid_c,ask_o,ask_h,ask_l,ask_c,bid_o,bid_h,bid_l,bid_c
0,2024-01-01T22:03:00.000000000Z,155.628,155.628,155.628,155.628,155.703,155.703,155.703,155.703,155.553,155.553,155.553,155.553
1,2024-01-01T22:05:00.000000000Z,155.659,155.659,155.659,155.659,155.734,155.734,155.734,155.734,155.584,155.584,155.584,155.584
2,2024-01-01T22:07:00.000000000Z,155.618,155.618,155.608,155.608,155.693,155.693,155.683,155.683,155.543,155.543,155.533,155.533
3,2024-01-01T22:09:00.000000000Z,155.610,155.610,155.610,155.610,155.682,155.682,155.682,155.682,155.539,155.539,155.539,155.539
4,2024-01-01T22:10:00.000000000Z,155.610,155.614,155.610,155.613,155.681,155.684,155.673,155.673,155.540,155.553,155.540,155.553
...,...,...,...,...,...,...,...,...,...,...,...,...,...
256248,2024-09-06T20:55:00.000000000Z,157.780,157.780,157.722,157.722,157.802,157.805,157.744,157.748,157.759,157.759,157.697,157.697
256249,2024-09-06T20:56:00.000000000Z,157.724,157.762,157.722,157.732,157.749,157.801,157.743,157.778,157.700,157.738,157.687,157.687
256250,2024-09-06T20:57:00.000000000Z,157.736,157.776,157.728,157.768,157.777,157.822,157.766,157.815,157.694,157.731,157.685,157.721
256251,2024-09-06T20:58:00.000000000Z,157.770,157.770,157.742,157.752,157.819,157.822,157.788,157.802,157.721,157.721,157.687,157.703
256252,2024-09-06T20:59:00.000000000Z,157.754,157.754,157.752,157.754,157.802,157.802,157.802,157.802,157.707,157.707,157.703,157.706

In [54]:
candles[0], candles[1]

IndexError: list index out of range

In [ ]:
import pandas as pd
df = pd.DataFrame.from_dict(candles_list).copy()
df

In [ ]:
fileName = f"{instrument}.pkl"
path  = "../data"
full_path = f'{path}/{fileName}'

In [47]:
# with open(full_path,'w') as f:
#     df.to_pickle(full_path)
df.to_pickle(full_path)

NameError: name 'full_path' is not defined

In [ ]:
new_df = pd.read_pickle(full_path)

In [ ]:
# with open(full_path,'w') as f:
#     df.to_pickle(full_path)

In [ ]:
mas =  [10,20,50,100,200]

In [ ]:
df_an  = new_df.copy()

In [ ]:
for i in mas:
    df_an[f'MA_{i}']= df_an['mid_o'].rolling(window=i).mean()

In [ ]:
df_an.dropna(inplace=True)

In [ ]:
df_an